#!/usr/bin/bash

BUILD=/var/_build
STORE=$BUILD/osbuild_store
HOST_STORE=/mnt/osbuild_store

mkdir -p $STORE/sources/org.osbuild.files $BUILD/output

# Copy reference sources from host
echo Copying Source files from host
cd $HOST_STORE/sources/org.osbuild.files || exit 2
cat /mnt/manifest.files | xargs cp -ran -t $STORE/sources/org.osbuild.files/

cp /mnt/manifest.json $BUILD/

rm -rf $BUILD/output
mkdir $BUILD/output

ARGS=
IFS=','
for e in $EXPORTS; do
    ARGS="$ARGS --export=$e"
done
unset IFS

echo Running osbuild in container
podman run -i -v /dev:/dev -v /mnt:/mnt -v /var:/var --privileged --rm --workdir $BUILD \
       --pull=never \
       quay.io/centos-sig-automotive/automotive-osbuild \
       \
       osbuild --store $STORE --output-dir $BUILD/output  --cache-max-size=2GB --checkpoint build $ARGS manifest.json
if test $? != 0 ; then
    exit 1
fi

echo Copying Output to host
mkdir -p /mnt/output
cd $BUILD/output/ || exit 3
tar cvf /mnt/output.tar .

exit 0
