version: '2'

mpp-vars:
  image_loopdev:
    mpp-eval: "{p.id: { 'type': 'org.osbuild.loopback', 'options': {'filename': 'disk.img', 'start': p.start, 'size': p.size}}  for p in image.layout.partitions}"
  image_loopdev_locked:
    mpp-eval: "{id: {**image_loopdev[id], 'lock': True} for id in image_loopdev.keys()}"
  # Either the raw root partition, or the root logical volume
  root_dev:
    mpp-if: use_luks
    then:
      type: org.osbuild.lvm2.lv
      parent: root-luks
      options:
        volume: root
    else:
      mpp-eval: image_loopdev[rootpart_label]
  # The luks2 physical device, should be named root-luks and references root-raw for the raw partition
  root_luksdev:
    type: org.osbuild.luks2
    parent: root-raw
    options:
      passphrase:
        mpp-eval: luks_passphrase

pipelines:
  - mpp-if: "_error(f'Rootfs contains denied rpms: {space.join(denied)}') if (denied := [rpm for rpm in denylist_rpms if rpm in rpms['rootfs']]) else False"
  - mpp-if: "_error(f'No separate partition for /var/qm, as required by --fusa') if use_fusa and use_qm and not _qm_use_separate_var else False"

  - name: image
    build: name:build
    stages:
      mpp-join:
        - - type: org.osbuild.truncate
            options:
              filename: disk.img
              size:
                mpp-eval: image.size
          - type: org.osbuild.sfdisk
            devices:
              device:
                type: org.osbuild.loopback
                options:
                  filename: disk.img
            options:
              mpp-format-json: '{image.layout}'
          - mpp-if: use_aboot and use_abootpart
            then:
              type: org.osbuild-auto.write-device
              devices:
                device:
                  mpp-eval: image_loopdev['boot_a']
              inputs:
                tree:
                  type: org.osbuild.tree
                  origin: org.osbuild.pipeline
                  references:
                    - name:image-tree
              options:
                from:
                  mpp-if: use_kernel_debug_package
                  then:
                    mpp-format-string: "input://tree/boot/aboot-{rpms['rootfs'][kernel_core_package].evra}+debug.img"
                  else:
                    mpp-format-string: "input://tree/boot/aboot-{rpms['rootfs'][kernel_core_package].evra}.img"
          - mpp-if: use_efipart
            then:
              type: org.osbuild.mkfs.fat
              devices:
                device:
                  mpp-eval: image_loopdev['efi']
              options:
                label: ESP
                volid: 7B7795E7
                # Usually disk geometry is obtained automatically, but some platforms
                # require a specific boot filesystem geometry in order to boot. This
                # allows you to setup the geometry of the disk.
                geometry:
                  mpp-if: "'efipart_geometry' in locals()"
                  then:
                    mpp-eval: efipart_geometry
          - mpp-if: use_bootpart
            then:
              type: org.osbuild.mkfs.ext4
              devices:
                device:
                  mpp-eval: image_loopdev['boot']
              options:
                uuid:
                  mpp-eval: bootfs_uuid
                label: boot
                lazy_init:
                  mpp-if: osbuild_major_version > 138
                  then: false
          - mpp-if: _use_separate_var and _varpart_size > 0
            then:
              type: org.osbuild.mkfs.ext4
              devices:
                device:
                  mpp-eval: image_loopdev['var']
              options:
                uuid:
                  mpp-eval: varpart_uuid
                label: var
                lazy_init:
                  mpp-if: osbuild_major_version > 138
                  then: false
          - mpp-if: _qm_use_separate_var and _qm_varpart_size > 0
            then:
              type: org.osbuild.mkfs.ext4
              devices:
                device:
                  mpp-eval: image_loopdev['qm_var']
              options:
                uuid:
                  mpp-eval: qm_varpart_uuid
                label: qm_var
                lazy_init:
                  mpp-if: osbuild_major_version > 138
                  then: false
        - mpp-if: use_luks
          then:
            - type: org.osbuild.luks2.format
              devices:
                device:
                  mpp-eval: image_loopdev_locked[rootpart_label]
              options:
                passphrase:
                  mpp-eval: luks_passphrase
                uuid:
                  mpp-eval: luks_uuid
                label: luks-rootfs
                pbkdf:
                  method: argon2i
                  memory: 32
                  parallelism: 1
                  iterations: 4
                integrity:
                  mpp-if: luks_use_integrity
                  then: hmac-sha256
            - type: org.osbuild.lvm2.create
              devices:
                root-raw:
                  mpp-eval: image_loopdev[rootpart_label]
                device:
                  mpp-eval: root_luksdev
              options:
                volumes:
                  - name: root
                    extents: 100%FREE
        - - type: org.osbuild.mkfs.ext4
            devices:
              root-raw:
                mpp-if: use_luks
                then:
                  mpp-eval: image_loopdev[rootpart_label]
              root-luks:
                mpp-if: use_luks
                then:
                  mpp-eval: root_luksdev
              device:
                mpp-eval: root_dev
            options:
              uuid:
                mpp-eval: rootfs_uuid
              label:
                mpp-if: not use_aboot
                then:
                  mpp-format-string: root
              lazy_init:
                mpp-if: osbuild_major_version > 138
                then: false
              verity: true
          - type: org.osbuild.copy
            inputs:
              tree:
                type: org.osbuild.tree
                origin: org.osbuild.pipeline
                references:
                  - name:image-tree
              build-tree:
                type: org.osbuild.tree
                origin: org.osbuild.pipeline
                references:
                  - name:build
              extra-tree:
                mpp-if: "'extra_image_source_' + image_mode in locals()"
                then:
                  type: org.osbuild.tree
                  origin: org.osbuild.pipeline
                  references:
                    - mpp-format-string: "name:{locals().get('extra_image_source_' + image_mode)}"
            options:
              paths:
                mpp-join:
                  - - from: input://tree/
                      to: mount://root/
                  - mpp-eval: extra_image_copy
            devices:
              efi:
                mpp-if: use_efipart
                then:
                  mpp-eval: image_loopdev['efi']
              boot:
                mpp-if: use_bootpart
                then:
                  mpp-eval: image_loopdev['boot']
              boot_a:
                mpp-if: use_abootpart
                then:
                  mpp-eval: image_loopdev['boot_a']
              boot_b:
                mpp-if: use_abootpart
                then:
                  mpp-eval: image_loopdev['boot_b']
              vbmeta_a:
                mpp-if: use_vbmetapart
                then:
                  mpp-eval: image_loopdev['vbmeta_a']
              vbmeta_b:
                mpp-if: use_vbmetapart
                then:
                  mpp-eval: image_loopdev['vbmeta_b']
              var:
                mpp-if: _use_separate_var and _varpart_size > 0
                then:
                  mpp-eval: image_loopdev['var']
              qm_var:
                mpp-if: _qm_use_separate_var and _qm_varpart_size > 0
                then:
                  mpp-eval: image_loopdev['qm_var']
              root:
                mpp-eval: root_dev
              root-raw:
                mpp-if: use_luks
                then:
                  mpp-eval: image_loopdev[rootpart_label]
              root-luks:
                mpp-if: use_luks
                then:
                  mpp-eval: root_luksdev
            mounts:
              - name: root
                type: org.osbuild.ext4
                source: root
                target: /
              - mpp-if: _use_separate_var and _varpart_size > 0
                then:
                  name: var
                  type: org.osbuild.ext4
                  source: var
                  target: /var
              - mpp-if: _qm_use_separate_var and _qm_varpart_size > 0
                then:
                  name: qm_var
                  type: org.osbuild.ext4
                  source: qm_var
                  target: /var/qm
              - mpp-if: use_bootpart
                then:
                  name: boot
                  type: org.osbuild.ext4
                  source: boot
                  target: /boot
              - mpp-if: use_efipart
                then:
                  name: efi
                  type: org.osbuild.fat
                  source: efi
                  target: /boot/efi

          - mpp-if: use_composefs and use_ostree
            then:
              type: org.osbuild.ostree.post-copy
              devices:
                root:
                  mpp-eval: root_dev
                root-raw:
                  mpp-if: use_luks
                  then:
                    mpp-eval: image_loopdev[rootpart_label]
                root-luks:
                  mpp-if: use_luks
                  then:
                    mpp-eval: root_luksdev
              mounts:
                - name: root
                  type: org.osbuild.ext4
                  source: root
                  target: /

          - mpp-if: use_luks
            then:
              type: org.osbuild.lvm2.metadata
              devices:
                root-raw:
                  mpp-eval: image_loopdev[rootpart_label]
                device:
                  mpp-eval: root_luksdev
              options:
                vg_name: osbuild
                creation_host: osbuild
                description: "Built with osbuild"

  - name: qcow2
    build: name:build
    stages:
      - type: org.osbuild.qemu
        inputs:
          image:
            type: org.osbuild.files
            origin: org.osbuild.pipeline
            references:
              name:image:
                file: disk.img
        options:
          filename: disk.qcow2
          format:
            type: qcow2
            compat: '1.1'

  - name: ext4
    build: name:build
    stages:
      - type: org.osbuild.truncate
        options:
          filename: rootfs.ext4
          size:
            mpp-eval: image.size
      - type: org.osbuild.mkfs.ext4
        devices:
          device:
            type: org.osbuild.loopback
            options:
              filename: rootfs.ext4
              start: 0
              size:
                mpp-format-int: "{int(image.size) // 512}"
        options:
          uuid:
            mpp-eval: rootfs_uuid
          label: root
          lazy_init:
            mpp-if: osbuild_major_version > 138
            then: false
          verity: true
      - type: org.osbuild.copy
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:image-tree
        options:
          paths:
            mpp-join:
              - - from: input://tree/
                  to: mount://root/
              - mpp-eval: locals().get('extra_image_copy_' + image_mode, [])
        devices:
          root:
            type: org.osbuild.loopback
            options:
              filename: rootfs.ext4
              start: 0
              size:
                mpp-format-int: "{int(image.size) // 512}"
        mounts:
          - name: root
            type: org.osbuild.ext4
            source: root
            target: /

      - mpp-if: use_composefs and use_ostree
        then:
          type: org.osbuild.ostree.post-copy
          devices:
            root:
              type: org.osbuild.loopback
              options:
                filename: rootfs.ext4
                start: 0
                size:
                  mpp-format-int: "{int(image.size) // 512}"
          mounts:
            - name: root
              type: org.osbuild.ext4
              source: root
              target: /

  - mpp-if: use_aboot
    then:
      name: aboot
      build: name:build
      stages:
        - type: org.osbuild.mkdir
          options:
            paths:
              - path: /images
        - type: org.osbuild.copy
          inputs:
            ext4:
              type: org.osbuild.tree
              origin: org.osbuild.pipeline
              references:
                - name:ext4
            tree:
              type: org.osbuild.tree
              origin: org.osbuild.pipeline
              references:
                - name:image-tree
          options:
            paths:
              - from: input://ext4/rootfs.ext4
                to: tree:///images/rootfs.img
              - from:
                  mpp-if: use_kernel_debug_package
                  then:
                    mpp-format-string: "input://tree/boot/aboot-{rpms['rootfs'][kernel_core_package].evra}+debug.img"
                  else:
                    mpp-format-string: "input://tree/boot/aboot-{rpms['rootfs'][kernel_core_package].evra}.img"
                to: tree:///images/aboot.img

  # This is essentially rootfs with no image-specific stuff like boot, etc, but with
  # some required extras.
  - name: raw-image-tree
    build: name:build
    stages:
      mpp-join:
        - - type: org.osbuild.mkdir
            options:
              paths:
                mpp-eval: extra_tree_dirs
          - type: org.osbuild.copy
            inputs:
              tree:
                type: org.osbuild.tree
                origin: org.osbuild.pipeline
                references:
                  - name:rootfs
              extra-tree:
                type: org.osbuild.tree
                origin: org.osbuild.pipeline
                references:
                  - name:extra-tree-content
            options:
              paths:
                mpp-join:
                  - - from: input://tree/
                      to: tree:///
                  - mpp-eval: extra_tree_content
        - mpp-eval: image_extra_stages
        - - type: org.osbuild.selinux
            options:
              file_contexts:
                mpp-format-string: etc/selinux/{selinux_policy}/contexts/files/file_contexts

  - name: container
    build: name:build
    stages:
      - type: org.osbuild.oci-archive
        inputs:
          base:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:raw-image-tree
        options:
          filename: container.tar
          architecture:
            mpp-eval: goarch
          config:
            Entrypoint:
              mpp-if: container_entrypoint
              then:
                mpp-eval: container_entrypoint
            Cmd:
              mpp-eval: container_cmd

  - name: tar
    build: name:build
    stages:
      - type: org.osbuild.tar
        inputs:
          tree:
            type: org.osbuild.tree
            origin: org.osbuild.pipeline
            references:
              - name:raw-image-tree
        options:
          filename: rootfs.tar
          root-node:
            mpp-if: not tar_paths
            then: omit
          paths:
            mpp-if: tar_paths
            then:
              mpp-eval: tar_paths

  - name: rpmlist
    runner: org.osbuild.centos9
    stages:
      - type: org.osbuild.copy
        inputs:
          inlinefile:
            type: org.osbuild.files
            origin: org.osbuild.source
            mpp-embed:
              id: rpmlist
              text:
                mpp-eval: |
                  _json.dumps(
                  {pipeline:{name:{'url':info.url,'arch':info.arch,'evr':info.evr,'license':getattr(info, 'license_tag', None),'summary':getattr(info, 'summary', None), 'sourcerpm':getattr(info, 'sourcerpm', None), 'buildtime':getattr(info, 'buildtime', None), 'vendor':getattr(info, 'vendor', None)} for (name, info) in rpms[pipeline].items()} for pipeline in rpms.keys()}
                  , indent=True, sort_keys=True)
        options:
          paths:
            - from:
                mpp-format-string: input://inlinefile/{embedded['rpmlist']}
              to: tree:///rpmlist
