# This is a qemu target similar to the "abootqemu",
# but using a dtb that enables kvm.
#
version: '2'
# To derive and override mpp vars we move the overrides to an include file
pipelines:
 - mpp-import-pipelines:
    path: abootqemu.ipp.yml
 - mpp-import-pipelines:
    path: include/_abootqemukvm.ipp.yml
