# Target for the TI J784S4XEVM Evaluation Board (https://www.ti.com/tool/J784S4XEVM)
version: '2'
mpp-vars:
  k3_board: 'j784s4_evm_gp'

# To derive and override mpp vars we move the overrides to an include file
pipelines:
  - mpp-import-pipelines:
      path: include/k3.ipp.yml
