# A target for the QC RIDESX4 board, Rev 3.
#
# The hardware is slightly different from previous revisions, and so this
# target inherits everything from the base QC RIDESX4 target configuration
# and overrides the device tree to reflect the hardware changes.
version: '2'
# To derive and override mpp vars we move the overrides to an include file
pipelines:
  - mpp-import-pipelines:
      path: ridesx4.ipp.yml
  - mpp-import-pipelines:
      path: include/_ridesx4_r3.ipp.yml
