# A target for the QC RIDESX4 board, Rev 3.
#
# The hardware is slightly different from previous revisions, and so this
# target inherits everything from the base QC RIDESX4 target configuration
# and overrides the device tree to reflect the hardware changes.
version: "2"

mpp-vars:
  aboot_dtb_file: "qcom/sa8775p-ride-r3.dtb"

# To derive and override mpp vars we move the overrides to an include file
pipelines:
  - mpp-import-pipelines:
      path: include/_ridesx4_common.ipp.yml
  - mpp-import-pipelines:
      path: include/_ridesx4.ipp.yml
